on: 
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:

jobs:
    check-upstream:
        runs-on: 'ubuntu-latest'
        steps:
            - run: sudo apt-get install reprepro
            - run: sudo apt-get install createrepo
            - run: sudo apt-get install curl
            - run: sudo apt-get install dpkg-dev
            - run: sudo apt-get install openssl
            - run: sudo apt-get install expect
            - run: sudo apt-get install debsigs
            - run: sudo chmod +x ./updaterepos.sh
            - run: ./updaterepos.sh
            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: pkgs
            
