on: 
    schedule:
        - cron: '0 0 * * 0'
    workflow_dispatch:
    workflow_call:
        secrets:
            KEY:
                description: 'Signing Encryiption Key'
                required: TRUE

jobs:
    check-upstream:
        runs-on: 'ubuntu-latest'
        env:
            KEY: ${{ secrets.KEY }}
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - run: sudo apt-get install reprepro
            - run: sudo apt-get install createrepo-c
            - run: sudo apt-get install curl
            - run: sudo apt-get install dpkg-dev
            - run: sudo apt-get install openssl
            - run: sudo apt-get install expect
            - run: sudo apt-get install debsigs
            - run: sudo chmod +x ./updaterepos.sh
            - run: sh ./updaterepos.sh
              env:
                KEY: ${{ secrets.KEY }}
            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: pkgs
            
